version: "3"

tasks:
  default:
    desc: Display available commands
    cmds:
      - task --list-all
    silent: true

  # Setup Commandes
  setup:
    desc: Bulild images and start database services
    cmds:
      - |
        docker compose build
        docker compose up -d scrap-db staging-db
        echo "✅ The database services are runing, next you can:"
        echo "  - Import database with '<service-db>:import' command."
        echo "  - Run a job with 'task run-job job=<jobName>' command."

  build:
    desc: Build docker images
    cmds:
      - docker compose build

  down:
    desc: Stop all services
    cmds:
      - docker compose down

  # Batch Commandes
  jobs:
    desc: Show jobs available in the batch application
    cmds:
      - |
        echo "=== Jobs available ==="
        echo "- hashingCardImageJob: Hash all card images and save them into iris database"
        echo "- scrapingCardJob: Scrap all cards from tcgAPI"
        echo "- scrapingPriceJob: Scrap all today prices from tcgAPI"
        echo "- scrapingPriceJobWithoutApi: Scrap all prices without using only staging database"
    siltent: true

  run-job:
    desc: Run a specific job in the batch application, use `task list-jobs` to see available jobs
    params:
      - name: job
        desc: Job to run
        type: choice
        options:
          - hashingCardImageJob
          - scrapingCardJob
          - scrapingPriceJob
          - scrapingPriceJobWithoutApi
        default: scrapingPriceJob
      - name: profile
        desc: Profil to use for the job
        type: choice
        options:
          - local
          - prod
          - test
        default: local
    cmds:
      - echo "Run {{.job}} with {{.profile}} profile"
      - docker compose run --rm app --spring.batch.job.name={{.job}} --spring.profiles.active={{.profile}}

  # Test Commandes
  test:
    desc: Setup and run tests
    cmds:
      - docker compose -f docker-compose.test.yml build
      - docker compose -f docker-compose.test.yml run --rm test

  # Database Commandes
  scrap-db:import:
    desc: Import scrap_db database from dump file
    cmds:
      - echo "Importing scrap_db database from dump file..."
      - |
        source .env && \
        echo "🔄 Starting import... " && \
        (docker compose exec -T scrap-db mysql -uroot -p"$LOOTER_SCRAP_DB_PASSWORD" $LOOTER_SCRAP_DB_NAME < ./scrap_db_dump.sql 2>&1) && \
        echo "✅ Import completed with success !"

  scrap-db:export:
    desc: Export scrap_db database into dump file
    cmds:
      - echo "Exporting scrap_db database into scrap_db_dump.sql..."
      - |
        source .env && \
        echo "🔄 Starting export... " && \
        (docker compose exec -T scrap-db mysqldump --databases $LOOTER_SCRAP_DB_NAME -uroot -p"$LOOTER_SCRAP_DB_PASSWORD" > ./scrap_db_dump.sql 2>/dev/null) && \
        echo "✅ Export completed with success into ./scrap_db_dump.sql !"

  staging-db:import:
    desc: Import staging_db database from dump file
    cmds:
      - echo "Importing staging_db database from dump file..."
      - |
        source .env && \
        echo "🔄 Starting import... " && \
        (docker compose exec -T staging-db mysql -uroot -p"$LOOTER_STAGING_DB_PASSWORD" $LOOTER_STAGING_DB_NAME < ./staging_db_dump.sql 2>&1) && \
        echo "✅ Import completed with success !"

  staging-db:export:
    desc: Export staging_db database into dump file
    cmds:
      - echo "Exporting staging_db database into staging_db_dump.sql..."
      - |
        source .env && \
        echo "🔄 Starting export... " && \
        (docker compose exec -T staging-db mysqldump --databases $LOOTER_STAGING_DB_NAME -uroot -p"$LOOTER_STAGING_DB_PASSWORD" > ./staging_db_dump.sql 2>/dev/null) && \
        echo "✅ Export completed with success into ./staging_db_dump.sql !"
