spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: looter
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/looter_scrap_db
      username: ${LOOTER_SCRAP_DB_USERNAME}
      password: ${LOOTER_SCRAP_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  batch:
    jdbc:
      initialize-schema: never

logging:
  level:
    com:
      sleeved:
        looter: INFO

looter:
  batch:
    chunksize: 10
  staging:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/looter_staging_db
      username: ${LOOTER_STAGING_DB_USERNAME}
      password: ${LOOTER_STAGING_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

atlas:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/sleeved_db
    username: ${SLEEVED_DB_USERNAME}
    password: ${SLEEVED_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

tcgplayer:
  api:
    key: ${TCGPLAYER_API_KEY}
    url:
      protocole: https
      domain: api.pokemontcg.io
      base: v2
    endpoints:
      cards:
        paginate: cards?page=%d&pageSize=%d&orderBy=set.releaseDate
        paginate-prices: cards?page=%d&pageSize=%d&orderBy=set.releaseDate&select=id,name,tcgplayer,cardmarket
        pagesize: 200
        page: 1
