spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: looter
  datasource:
    hikari:
      jdbc-url: ${LOOTER_SCRAP_JDBC_URL}
      username: ${LOOTER_SCRAP_DB_USERNAME}
      password: ${LOOTER_SCRAP_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
  batch:
    jdbc:
      initialize-schema: never

server:
  port: 5001

logging:
  level:
    com:
      sleeved:
        looter: DEBUG

looter:
  batch:
    chunksize: 10
  staging:
    datasource:
      jdbc-url: ${LOOTER_STAGING_JDBC_URL}
      username: ${LOOTER_STAGING_DB_USERNAME}
      password: ${LOOTER_STAGING_DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

atlas:
  datasource:
    jdbc-url: ${SLEEVED_DB_JDBC_URL}
    username: ${SLEEVED_DB_USERNAME}
    password: ${SLEEVED_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

iris:
  datasource:
    jdbc-url: ${IRIS_DB_JDBC_URL}
    username: ${IRIS_DB_USERNAME}
    password: ${IRIS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  api:
    url:
      protocole: http
      domain: iris-api:8083
      base: api/v1
      endpoint:
        hash: images/hash/url

tcgplayer:
  api:
    key: ${TCGPLAYER_API_KEY}
    url:
      protocole: https
      domain: api.pokemontcg.io
      base: v2
    endpoints:
      cards:
        paginate: cards?page=%d&pageSize=%d&orderBy=set.releaseDate
        paginate-prices: cards?page=%d&pageSize=%d&orderBy=set.releaseDate&select=id,name,tcgplayer,cardmarket
        pagesize: 200
        page: 1
