#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ">> Start Checkstyle..."
mvn checkstyle:check

if [ $? -ne 0 ]; then
  echo "❌ Checkstyle violation detected. Commit canceled."
  exit 1
fi

echo "✅ Checkstyle passed. Commit allowed."
exit 0
