#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ">> Lancement de Checkstyle..."
mvn checkstyle:check

if [ $? -ne 0 ]; then
  echo "❌ Checkstyle a détecté des violations. Commit annulé."
  exit 1
fi

echo "✅ Checkstyle passed. Commit autorisé."
exit 0
